---
- name: Install the apt repository
  become: true
  ansible.builtin.shell: /home/{{ username }}/Projects/configs/scripts/1password-repo.sh

- name: Install 1Password
  become: true
  ansible.builtin.apt:
    pkg:
      - 1password
    state: latest
