---
- name: Install a chosen shell
  become: true
  ansible.builtin.apt:
    pkg:
      - "{{ shell }}"
    state: latest

- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: "/usr/local/share/fonts/m/"
    state: directory

- name: FiraCode exists
  become: true
  ansible.builtin.shell: "touch -a /usr/local/share/fonts/f/ && ls /usr/local/share/fonts/f/FiraCodeNerdFont_*"
  register: fira_code_exists

- name: Download FiraCode
  when: fira_code_exists is failed
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip"
    dest: "/usr/local/share/fonts/f/"
    remote_src: yes

- name: Setup terminal
  ansible.builtin.meta: noop # TODO Actually setup terminal (for real)

- name: Configure zsh
  ansible.builtin.import_tasks:
    file: tasks/subtasks/zsh.yml
  when: shell == "zsh"

- name: Configure fish
  ansible.builtin.import_tasks:
    file: tasks/subtasks/fish.yml
  when: shell == "fish"

- name: Set default shell
  become: true
  ansible.builtin.shell: "chsh -s /usr/bin/{{ shell }} {{ username }}"

- name: Install Helix
  ansible.builtin.import_tasks:
    file: tasks/subtasks/helix.yml

- name: Install VSCode
  ansible.builtin.import_tasks:
    file: tasks/subtasks/vscode.yml

- name: Install 1Password
  ansible.builtin.import_tasks:
    file: tasks/subtasks/1password.yml
