---
  - name: Install a chosen shell
    become: true
    ansible.builtin.apt:
      pkg:
        - "{{ shell }}"
      state: latest

  - name: Configure zsh
    ansible.builtin.import_tasks:
      file: tasks/subtasks/zsh.yml
    when: shell == "zsh"

  - name: Configure fish
    ansible.builtin.import_tasks:
      file: tasks/subtasks/fish.yml
    when: shell == "fish"
