---
- name: Install the apt repository
  become: true
  ansible.builtin.shell: /home/{{ username }}/Projects/configs/scripts/spotify-repo.sh

- name: Install Spotify
  become: true
  ansible.builtin.apt:
    pkg:
      - spotify-client
    state: latest
