---
  - name: Download Fisher
    ansible.builtin.shell: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

  - name: Install Tide
    ansible.builtin.shell: fisher install IlanCosman/tide@v6
 
  - name: Configure Tide
    ansible.builtin.shell: tide configure --auto --style=Rainbow --prompt_colors='True color' --show_time='24-hour format' --rainbow_prompt_separators=Round --powerline_prompt_heads=Round --powerline_prompt_tails=Round --powerline_prompt_style='Two lines, character and frame' --prompt_connection=Dotted --powerline_right_prompt_frame=No --prompt_connection_andor_frame_color=Lightest --prompt_spacing=Sparse --icons='Many icons' --transient=No

  - name: Install fonts for Powerlevel10k
    ansible.builtin.meta:
      noop # TODO Actually install fonts (for real)
