---
- name: Download Fisher
  ansible.builtin.shell: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
  args:
    executable: /bin/fish

- name: Install Tide
  ansible.builtin.shell: fisher install IlanCosman/tide@v6
  args:
    executable: /bin/fish

- name: Configure Tide
  ansible.builtin.script: ~/Projects/configs/configs/fish/tide-config.sh
