- name: Install Flatpak
  become: true
  ansible.builtin.apt:
    pkg:
      - flatpak
    state: latest

- name: Configure Flatpak remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
