---
- name: Prerequisites
  hosts: localhost

  tasks:
  - name: Install prerequisites
    become: true
    ansible.builtin.apt:
      pkg:
        - build-essential
        - wget
        - curl
        - gpg
        - apt-transport-https
        - git
      state: latest

  - name: Install Flatpak
    ansible.builtin.include_tasks:
      file: components/flatpak.yml
  
  - name: Make "Projects" folder
    ansible.builtin.file:
      path: ~/Projects
      state: directory

  - name: Clone your repo with configs
    ansible.builtin.git:
      repo: 'https://github.com/RayChimera/configs'
      dest: ~/Projects/configs/
