---
- name: Choose what to install
  hosts: localhost
  vars_prompt:  
  - name: shell
    prompt: What shell to install?
    private: false
    default: zsh

  tasks:
  - ansible.builtin.import_tasks: tasks/prerequisites.yml
  - ansible.builtin.import_tasks: tasks/shells.yml
