---
- name: Choose what to install
  hosts: localhost
  vars_prompt:  
  - name: shell
    prompt: What shell to install?
    private: false
    default: zsh

- ansible.builtin.import_playbook: prerequisites.yml
- ansible.builtin.import_playbook: shells.yml
  vars:
    shell: "{{ shell }}"
