---
- name: Setting up a shell
  hosts: localhost

  tasks:
  - name: Display all variables/facts known for a host
    debug:
      var: hostvars[inventory_hostname]
    tags: debug_info

  - name: Install a chosen shell
    become: true
    ansible.builtin.apt:
      pkg:
        - "{{ shell }}"
      state: latest
